name: CI

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit

      - name: Run PHPCS
        run: ./vendor/bin/phpcs --standard=phpcs.xml

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse -c phpstan.neon
